### ISSUE TITLE
alphafold

### ISSUE THREAD

**Issue by evelynmitchell** [colbyford/AlphaFold3-Docker#1]
I notice you install https://github.com/aqlaboratory/openfold
Is that a requirement?

**Comment by colbyford** [comment]
> I notice you install https://github.com/aqlaboratory/openfold Is that a requirement?

Yes, the `kyegomez` repo says that it needs openfold in the pyproject.toml, but pip installs v0.0.1 of it.
https://github.com/kyegomez/AlphaFold3/blob/main/pyproject.toml#L29

Then, this old version causes an issue with a missing `get_nvidia_cc()` function when installing. So, as a work around, I am installing from their git repo.

I think the expectation is that this dependency will be removed soon.

**Comment by evelynmitchell** [comment]
Thanks. That looks good.

Evelyn
